name: cedar
description: Implementation of the Cedar policy language in Dart.
version: 0.2.1
repository: https://github.com/celest-dev/cedar-dart/tree/main/packages/cedar

environment:
  sdk: ^3.3.0

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.1
  characters: ^1.3.0
  collection: ^1.18.0
  decimal: ^3.0.2
  fixnum: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.11.0
  protobuf: ^3.1.0
  source_span: ^1.10.0
  string_scanner: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1
  cedar_tests:
    path: ../cedar_tests
  lints: ^4.0.0
  test: ^1.25.8
