name: cedar
description: Implementation of the Cedar policy language in Dart.
version: 0.2.2
repository: https://github.com/celest-dev/cedar-dart/tree/main/packages/cedar

environment:
  sdk: ^3.3.0

dependencies:
  built_collection: ^5.1.0
  built_value: ^8.9.0
  characters: ^1.3.0
  collection: ^1.18.0
  decimal: ^3.0.0
  fixnum: ^1.1.0
  json_annotation: ^4.9.0
  meta: ^1.11.0
  protobuf: ^3.1.0
  source_span: ^1.10.0
  string_scanner: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.12
  built_value_generator: ^8.9.2
  cedar_tests:
    path: ../cedar_tests
  lints: ^4.0.0
  test: ^1.25.8
