name: cedar_ffi
description: FFI bindings for the Cedar policy language, written in Rust.
version: 0.2.1
repository: https://github.com/celest-dev/cedar-dart/tree/main/packages/cedar_ffi

environment:
  sdk: ^3.8.0-278.2.beta

dependencies:
  cedar: ^0.2.0
  ffi: ^2.1.0
  meta: ^1.10.0
  native_assets_cli: ^0.16.0
  native_toolchain_c: ">=0.13.0 <0.18.0"

dev_dependencies:
  cedar_tests:
    path: ../cedar_tests
  ffigen: ^18.0.0
  lints: ">=5.0.0 <7.0.0"
  path: ^1.9.0
  test: ^1.26.0
