name: example
description: An example of the cedar_ffi library.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  cedar:
    path: ../../cedar
  cedar_ffi:
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
