[package]
name = "cedar-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1.0" }
cedar-policy = { version = "3.4" }
log = "0.4"
once_cell = "1.21"
serde = "1.0"
serde_json = "1.0"
simple_logger = "5.0"

[build-dependencies]
build-target = "0.4"
cbindgen = "0.29"
