name: cedar_ffi
on:
  pull_request:
    paths:
      - ".github/workflows/cedar_ffi.yaml"
      - "packages/cedar/**"
      - "packages/cedar_ffi/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: packages/cedar_ffi

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    # TODO(dnys1): Speed up Rust builds
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # 1.7.1
        with:
          # Native assets is only enabled on dev/main channels for now.
          sdk: dev
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@ab6845274e2ff01cd4462007e1a9d9df1ab49f42 # 1.14.0
      - name: Get Packages
        run: dart pub get
      - name: Test
        run: dart --enable-experiment=native-assets test --fail-fast
        working-directory: packages/cedar_ffi
