name: cedar_ffi
on:
  pull_request:
    paths:
      - ".github/workflows/cedar_ffi.yaml"
      - "packages/cedar/**"
      - "packages/cedar_ffi/**"

# Prevent duplicate runs due to Graphite
# https://graphite.dev/docs/troubleshooting#why-are-my-actions-running-twice
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - windows-latest
    runs-on: ${{ matrix.os }}
    # TODO(dnys1): Speed up Rust builds
    timeout-minutes: 15
    steps:
      - name: Git Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7
        with:
          submodules: true
      - name: Setup Dart
        uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672 # main
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc # 1.9.0
      - name: Get Packages
        working-directory: packages/cedar_ffi
        run: dart pub get
      - name: Test
        working-directory: packages/cedar_ffi
        run: dart --enable-experiment=native-assets test --fail-fast
