name: cedar (submodule)
on:
  schedule:
    - cron: "0 13 * * *" # Every day at 06:00 PST

# Needed for creating PRs
permissions:
  contents: write
  pull-requests: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Git Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # 4.1.5
        with:
          submodules: recursive
      - name: Setup Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # 2.16.0
        with:
          cache: true
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@b113a30d27a8e59c969077c0a0168cc13dab5ffc # 1.8.0
        with:
          cache-workspaces: |
            ./
            ./packages/cedar_ffi
            ./packages/cedar_ffi/src
      - name: Update submodule
        id: update
        run: |
          git submodule update --remote cedar
          [[ -n "$(git status --porcelain)" ]] && echo "needsUpdate=true" >> $GITHUB_OUTPUT
      - name: Cargo Check
        if: steps.update.outputs.needsUpdate
        run: cargo check
      - name: Get Packages
        if: steps.update.outputs.needsUpdate
        working-directory: packages/cedar_ffi
        run: dart pub upgrade
      - name: Test
        if: steps.update.outputs.needsUpdate
        working-directory: packages/cedar_ffi
        run: dart --enable-experiment=native-assets test
      - name: Create PR
        if: steps.update.outputs.needsUpdate
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # 6.0.5
        with:
          base: main
          branch: "chore/deps/cedar-submodule"
          branch-suffix: timestamp
          title: "chore(deps): Update `cedar` submodule"
          body: Updates the cedar submodule to the current `main`
